- name: build
  desc: "Run through the build process, including testing."
  shell:
    - ./fatpack.sh
    - dzil test
    - dzil build
- name: test
  desc: "Just test the changes"
  shell:
    - dzil test
- name: release
  desc: "Publish App::Dex to CPAN"
  shell:
    - dzil release
- name: clean
  desc: "Remove artifacts"
  shell:
    - dzil clean
# rm -rf App-dex-*.tar.gz MANIFEST META.yml MYMETA.* Makefile blib Makefile.old pm_to_blib
- name: authordeps
  desc: "Install distzilla and dependencies"
  shell:
    - cpanm Dist::Zilla
    - dzil authordeps --missing | cpanm
    - dzil listdeps --develop --missing | cpanm
